jgi-kbase/AssemblyHomologyService

- src/us/kbase/assemblyhomology/minhash/MinHashDBLocation.java
- src/us/kbase/assemblyhomology/minhash/MinHashDistance.java
- src/us/kbase/assemblyhomology/minhash/MinHashParameters.java
- src/us/kbase/assemblyhomology/minhash/MinHashSketchDatabase.java
Since the file location is being passed to an exec() should double check
it's a legit file at some point
Also other minor fixes.
> SCT-890 Check DB file exists

- README.md
- src/us/kbase/assemblyhomology/minhash/MinHashParameters.java
- src/us/kbase/assemblyhomology/minhash/MinHashSketchDatabase.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
Also rename hashCount to sketchSize
> Add some docs, bugfix

- README.md
- src/us/kbase/assemblyhomology/core/DataSourceID.java
- src/us/kbase/assemblyhomology/core/LoadID.java
- src/us/kbase/assemblyhomology/core/Name.java
- src/us/kbase/assemblyhomology/core/Namespace.java
- src/us/kbase/assemblyhomology/core/NamespaceID.java
- src/us/kbase/assemblyhomology/core/exceptions/AssemblyHomologyException.java
- src/us/kbase/assemblyhomology/core/exceptions/ErrorType.java
- src/us/kbase/assemblyhomology/core/exceptions/IllegalParameterException.java
- src/us/kbase/assemblyhomology/core/exceptions/MissingParameterException.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/assemblyhomology/storage/AssemblyHomologyStorage.java
- src/us/kbase/assemblyhomology/util/Util.java
Still needs an implementation
Starts setting up the exception handling, similar to the auth service
with error codes
> SCT-898 Add create/update/get namespace storage API

- src/us/kbase/assemblyhomology/core/Namespace.java
- src/us/kbase/assemblyhomology/core/SequenceMetadata.java
- src/us/kbase/assemblyhomology/storage/mongo/Fields.java
- src/us/kbase/assemblyhomology/storage/mongo/MongoAssemblyHomologyStorage.java
> SCT-889 Add creation date to namespaces and sequence metadata

- src/us/kbase/assemblyhomology/load/SeqMetaLoadInfo.java
Load will actually be a file of json docs
> SCT-903 Load sequence meta info from string

- src/us/kbase/assemblyhomology/load/Loader.java
- src/us/kbase/assemblyhomology/minhash/MinHashImplementation.java
- src/us/kbase/assemblyhomology/util/Restreamable.java
> SCT-903 Add loader

- .classpath
- README.md
- build.xml
- src/us/kbase/assemblyhomology/cli/AssemblyHomologyCLI.java
- war/web.xml
Got the main CLI guts working, need to actually make the load command do
something
Also adds a few files the service will need, although they're unused now
> SCT-903 Add start of a CLI

- README.md
- src/us/kbase/assemblyhomology/cli/AssemblyHomologyCLI.java
- src/us/kbase/assemblyhomology/load/NamespaceLoadInfo.java
Also make a default location for the config file.
> SCT-903 Add data load instructions for the CLI

- .classpath
- src/us/kbase/assemblyhomology/core/AssemblyHomology.java
- src/us/kbase/assemblyhomology/core/SequenceMatches.java
- src/us/kbase/assemblyhomology/core/SequenceMetadata.java
- src/us/kbase/assemblyhomology/minhash/MinHashDistanceSet.java
- src/us/kbase/assemblyhomology/minhash/MinHashImplementationFactory.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/assemblyhomology/minhash/mash/MashFactory.java
- src/us/kbase/assemblyhomology/storage/mongo/MongoAssemblyHomologyStorage.java
For now, just get a namespace and measure an input sequence against a
namespace.
Also adds a bunch of service jars
> SCT-936 Add business logic

- src/us/kbase/assemblyhomology/cli/AssemblyHomologyCLI.java
- src/us/kbase/assemblyhomology/core/AssemblyHomologyBuilder.java
Currently used by CLI, will be used by service.
> SCT-934 Add a common builder for the assembly homology app

- .classpath
- build.xml
- src/us/kbase/assemblyhomology/cli/AssemblyHomologyCLI.java
- src/us/kbase/assemblyhomology/config/AssemblyHomologyConfig.java
- src/us/kbase/assemblyhomology/service/LoggingFilter.java
- src/us/kbase/assemblyhomology/service/SLF4JAutoLogger.java
Untested so far, but want to commit what I've got.
> SCT-934 Add logging filter

- src/us/kbase/assemblyhomology/core/exceptions/NoDataException.java
- src/us/kbase/assemblyhomology/core/exceptions/NoSuchNamespaceException.java
- src/us/kbase/assemblyhomology/core/exceptions/NoSuchSequenceException.java
- src/us/kbase/assemblyhomology/service/Fields.java
- src/us/kbase/assemblyhomology/service/exceptions/ErrorMessage.java
- src/us/kbase/assemblyhomology/service/exceptions/ExceptionHandler.java
- src/us/kbase/assemblyhomology/storage/mongo/MongoAssemblyHomologyStorage.java
Not tested as yet, but want to commit what I've got.
> SCT-934 Add exception handler.

- README.md
- src/us/kbase/assemblyhomology/service/exceptions/ErrorMessage.java
- src/us/kbase/assemblyhomology/service/exceptions/ExceptionHandler.java
> Add developer docs

- README.md
- src/us/kbase/assemblyhomology/core/AssemblyHomology.java
- src/us/kbase/assemblyhomology/minhash/MinHashImplementationFactory.java
- src/us/kbase/assemblyhomology/minhash/MinHashImplementationInformation.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/assemblyhomology/minhash/mash/MashFactory.java
- src/us/kbase/assemblyhomology/service/AssemblyHomologyService.java
- src/us/kbase/assemblyhomology/service/Fields.java
- src/us/kbase/assemblyhomology/service/api/Namespaces.java
- src/us/kbase/assemblyhomology/service/api/ServicePaths.java
Example:
`$ curl -X POST -T kb_refseq_ci_1000_15792_446_1.msh http://localhost:20000/namespace /mynamespace/search | python -m json.tool`
> SCT-934 Add remote sketching.

- README.md
- src/us/kbase/assemblyhomology/core/AssemblyHomology.java
- src/us/kbase/assemblyhomology/core/Namespace.java
- src/us/kbase/assemblyhomology/core/SequenceMatches.java
- src/us/kbase/assemblyhomology/load/Loader.java
- src/us/kbase/assemblyhomology/load/NamespaceLoadInfo.java
- src/us/kbase/assemblyhomology/minhash/MinHashDBLocation.java
- src/us/kbase/assemblyhomology/minhash/MinHashDistance.java
- src/us/kbase/assemblyhomology/minhash/MinHashDistanceSet.java
- src/us/kbase/assemblyhomology/minhash/MinHashImplementation.java
- src/us/kbase/assemblyhomology/minhash/MinHashSketchDBName.java
- src/us/kbase/assemblyhomology/minhash/MinHashSketchDatabase.java
- src/us/kbase/assemblyhomology/minhash/exceptions/IncompatibleSketchesException.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/assemblyhomology/service/Fields.java
- src/us/kbase/assemblyhomology/service/api/Namespaces.java
- src/us/kbase/assemblyhomology/storage/mongo/MongoAssemblyHomologyStorage.java
- src/us/kbase/test/assemblyhomology/StandaloneAssemblyHomologyServer.java
TODO:
In future, supporting multiple kmer sizes would make this more useful.
> SCT-967 Search across namespaces

- README.md
- src/us/kbase/assemblyhomology/load/Loader.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/assemblyhomology/service/api/Namespaces.java
- src/us/kbase/assemblyhomology/storage/mongo/MongoAssemblyHomologyStorage.java
Allows supporting of multiple kmer sizes without changing db schema
> Fix loader, store kmersize in list

- .travis.yml
currently nuking auth2 coverage
> Change codecov token

- README.md
- src/us/kbase/assemblyhomology/minhash/MinHashSketchDatabase.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
Must've been thinking of sourmash
> Mash doesn't support multiple kmer sizes / db

- src/us/kbase/assemblyhomology/service/LoggingFilter.java
> Switch LoggingFilter to constructor injection

- .classpath
- build.xml
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/assemblyhomology/util/CappedTreeSet.java
- src/us/kbase/test/assemblyhomology/TestCommon.java
- src/us/kbase/test/assemblyhomology/util/CappedTreeSetTest.java
Works in eclipse and ant
TODO finish CTS test
> SCT-966 Get test rig working

- .classpath
- README.md
- build.xml
- src/us/kbase/assemblyhomology/util/FileOpener.java
- src/us/kbase/assemblyhomology/util/PathRestreamable.java
- src/us/kbase/assemblyhomology/util/Restreamable.java
- src/us/kbase/test/assemblyhomology/util/PathRestreamableTest.java
> SCT-966 Add tests for PathRestreamable

- README.md
- build.xml
- src/us/kbase/assemblyhomology/util/Util.java
- src/us/kbase/test/assemblyhomology/TestCommon.java
- src/us/kbase/test/assemblyhomology/util/UtilTest.java
Also add docs for the server root node.
> SCT-966 Add tests for the Util class.

- build.xml
- src/us/kbase/assemblyhomology/build/AssemblyHomologyBuilder.java
- src/us/kbase/assemblyhomology/cli/AssemblyHomologyCLI.java
- src/us/kbase/assemblyhomology/core/Name.java
- src/us/kbase/assemblyhomology/service/AssemblyHomologyService.java
- src/us/kbase/test/assemblyhomology/core/NameTest.java
Builder isn't really part of core code
> SCT-966 Add name tests & move builder

- src/us/kbase/assemblyhomology/core/AssemblyHomology.java
- src/us/kbase/assemblyhomology/core/SequenceMatches.java
- src/us/kbase/assemblyhomology/core/exceptions/ErrorType.java
- src/us/kbase/assemblyhomology/core/exceptions/IncompatibleNamespacesException.java
- src/us/kbase/assemblyhomology/core/exceptions/IncompatibleSketchesException.java
- src/us/kbase/assemblyhomology/service/api/Namespaces.java
- src/us/kbase/test/assemblyhomology/TestCommon.java
- src/us/kbase/test/assemblyhomology/core/AssemblyHomologyTest.java
- src/us/kbase/test/assemblyhomology/core/SequenceMatchesTest.java
Also a good bit of refactoring for testability & exception handling.
> SCT-966 Finish AssemblyHomlogy tests.

- README.md
- build.xml
- src/us/kbase/assemblyhomology/service/exceptions/ErrorMessage.java
- src/us/kbase/assemblyhomology/service/exceptions/ExceptionHandler.java
- src/us/kbase/test/assemblyhomology/service/exceptions/ErrorMessageTest.java
> SCT-966 Add ErrorMessage test

- Dockerfile
- RELEASE_NOTES.md
- deploy.cfg.example
- src/us/kbase/assemblyhomology/build/AssemblyHomologyBuilder.java
- src/us/kbase/assemblyhomology/cli/AssemblyHomologyCLI.java
- src/us/kbase/assemblyhomology/config/AssemblyHomologyConfig.java
- src/us/kbase/assemblyhomology/core/AssemblyHomology.java
- src/us/kbase/assemblyhomology/core/SequenceMatches.java
- src/us/kbase/assemblyhomology/minhash/MinHashDBLocation.java
- src/us/kbase/assemblyhomology/minhash/MinHashDistance.java
- src/us/kbase/assemblyhomology/minhash/MinHashImplementationFactory.java
- src/us/kbase/assemblyhomology/minhash/MinHashParameters.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/assemblyhomology/minhash/mash/MashFactory.java
- src/us/kbase/assemblyhomology/service/exceptions/ErrorMessage.java
- src/us/kbase/assemblyhomology/storage/AssemblyHomologyStorage.java
- src/us/kbase/assemblyhomology/storage/mongo/MongoAssemblyHomologyStorage.java
- src/us/kbase/assemblyhomology/util/FileOpener.java
- src/us/kbase/test/assemblyhomology/config/AssemblyHomologyConfigTest.java
- src/us/kbase/test/assemblyhomology/core/AssemblyHomologyTest.java
- src/us/kbase/test/assemblyhomology/minhash/mash/MashFactoryTest.java
- src/us/kbase/test/assemblyhomology/minhash/mash/MashTest.java
Tested the mash timeout manually.
The dockerfile changes were contributed by @scanon.
Also some documentation fixes.
> SCT-1267 Make Mash timeout configurable + more

- build.xml
- src/us/kbase/assemblyhomology/core/AssemblyHomology.java
- src/us/kbase/assemblyhomology/core/Namespace.java
- src/us/kbase/assemblyhomology/minhash/DefaultDistanceFilter.java
- src/us/kbase/assemblyhomology/minhash/MinHashDistanceCollector.java
- src/us/kbase/assemblyhomology/minhash/MinHashDistanceFilter.java
- src/us/kbase/assemblyhomology/minhash/MinHashImplementation.java
- src/us/kbase/assemblyhomology/minhash/mash/Mash.java
- src/us/kbase/test/assemblyhomology/core/AssemblyHomologyTest.java
- src/us/kbase/test/assemblyhomology/minhash/DefaultDistanceFilterTest.java
- src/us/kbase/test/assemblyhomology/minhash/mash/MashTest.java
rather than a single collector, that won't work.
> SCT-1348 Add per namespace filters

- .classpath
- .travis.yml
- build.xml
- src/us/kbase/assemblyhomology/build/AssemblyHomologyBuilder.java
- src/us/kbase/assemblyhomology/storage/mongo/MongoAssemblyHomologyStorage.java
- src/us/kbase/test/assemblyhomology/storage/MongoAssemblyHomologyStorageStartupTest.java
> Update mongo driver to latest version
